name: Build Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Image
      uses: podman/build-push-action@v2.1.0
      with:
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/akarinliu/flarum:latest
        push: true
        push_secret: ${{ secrets.GITHUB_TOKEN }}